cora:
  dataset: Cora
  device: 2
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.85
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.31
  ch_decoder_layers: 3
  ch_decoder_dropout: 0.54
  nb_size: 50
  ncaps: 16
  nlayer: 5
  max_iter: 10
  hsic_lamb: 0.001225
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.01
  node_lr_min: 0.01
  mask_ratio: 0.7
  recon_alpha: 0.00989
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 5e-05
  nodeclas_weight_decay: 0.0023
  epochs: 140
  save_path: model_nodeclas.pth
  bn: True

citeseer:
  dataset: Citeseer
  device: 3
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.81
  decoder_hidden: 32
  decoder_layers: 3
  decoder_dropout: 0.26
  ch_decoder_layers: 1
  ch_decoder_dropout: 0.49
  nb_size: 50
  ncaps: 16
  nlayer: 4
  max_iter: 6
  hsic_lamb: 1.8e-06
  link_lr_max: 0.01
  link_lr_min: 0.01
  node_lr_max: 0.01
  node_lr_min: 0.01
  mask_ratio: 0.7
  recon_alpha: 0.77
  batch_size: 65536
  l2_normalize: True
  alpha_l: 2
  weight_decay: 0.00032
  nodeclas_weight_decay: 0.22
  epochs: 179
  save_path: model_nodeclas.pth


pubmed:
  count: 815
  dataset: Pubmed
  device: 0
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.43
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.4
  ch_decoder_layers: 4
  ch_decoder_dropout: 0.23
  nb_size: 50
  ncaps: 16
  nlayer: 5
  max_iter: 8
  hsic_lamb: 2.4e-05
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  mask_ratio: 0.7
  recon_alpha: 0.6
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 0.00089
  nodeclas_weight_decay: 0.00109
  epochs: 65
  save_path: model_nodeclas.pth

photo:
  dataset: Photo
  device: 1
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.58
  decoder_hidden: 64
  decoder_layers: 5
  decoder_dropout: 0.47
  ch_decoder_layers: 5
  ch_decoder_dropout: 0.4
  nb_size: 50
  ncaps: 32
  nlayer: 5
  max_iter: 7
  hsic_lamb: 0.000462
  link_lr_max: 0.005
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  mask_ratio: 0.7
  recon_alpha: 0.00838
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 8e-06
  nodeclas_weight_decay: 4.56e-05
  epochs: 104
  save_path: model_nodeclas.pth

computers:
  dataset: Computers
  device: 2
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.69
  decoder_hidden: 64
  decoder_layers: 3
  decoder_dropout: 0.42
  ch_decoder_layers: 3
  ch_decoder_dropout: 0.16
  nb_size: 30
  ncaps: 32
  nlayer: 4
  max_iter: 8
  hsic_lamb: 0.000258
  link_lr_max: 0.01
  link_lr_min: 0.001
  node_lr_max: 0.1
  node_lr_min: 0.001
  mask_ratio: 0.7
  original_lamb: 0.4
  batch_size: 65536
  l2_normalize: True
  alpha_l: 3
  weight_decay: 9.2e-05
  nodeclas_weight_decay: 7.1e-05
  epochs: 147
  save_path: model_nodeclas.pth

wikics:
  dataset: WikiCS
  mask: Path
  device: 0
  encoder_hidden: 512
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.42
  decoder_hidden: 32
  decoder_layers: 2
  decoder_dropout: 0.6
  ch_decoder_layers: 3
  ch_decoder_dropout: 0.31
  nb_size: 70
  ncaps: 32
  nlayer: 4
  max_iter: 6
  hsic_lamb: 4.3e-05
  link_lr_max: 0.1
  link_lr_min: 0.005
  node_lr_max: 0.1
  node_lr_min: 0.001
  grad_norm: 1.0
  mask_ratio: 0.7
  recon_alpha: 0.0005
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 8.4e-05
  nodeclas_weight_decay: 2.9e-05
  epochs: 145
  save_path: model_nodeclas.pth

arxiv:
  dataset: Arxiv
  mask: Path
  device: 2
  encoder_hidden: 256
  encoder_out: 512
  encoder_layers: 1
  encoder_dropout: 0.11
  decoder_hidden: 128
  decoder_layers: 3
  decoder_dropout: 0
  ch_decoder_layers: 3
  ch_decoder_dropout: 0.25
  nb_size: 10
  ncaps: 16
  nlayer: 5
  max_iter: 7
  hsic_lamb: 0.00305
  link_lr_max: 0.0005
  link_lr_min: 0.0005
  node_lr_max: 0.1
  node_lr_min: 0.001
  mask_ratio: 0.7
  recon_alpha: 0.00841
  batch_size: 65536
  l2_normalize: True
  alpha_l: 1
  weight_decay: 0.00051
  nodeclas_weight_decay: 0
  epochs: 76
  save_path: model_nodeclas.pth




